stages:
  - build
  - test

golangci-lint v1.50.1:
  stage: test
  image: golangci/golangci-lint:v1.50.1
  script:
    - golangci-lint --version
    - golangci-lint run -v

staticcheck v0.3.3:
  stage: test
  image: golang:1.19
  script:
    - go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
    - staticcheck ./...

compile go 1.19:
  stage: build
  image: golang:1.19
  script:
    - go build -v ./...

race detector:
  stage: test
  image: golang:1.19
  script:
    - go build -race ./...

unittests:
  stage: test
  image: golang:1.19
  script:
    - go test -v ./...

coverage:
  stage: test
  image: golang:1.19
  script:
    - go test ./... -coverprofile=coverage.txt -covermode count
    - go install github.com/boumenot/gocover-cobertura@latest
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

integration test:
  stage: test
  image: golang:1.19
  before_script:
    - apt update
    - apt install -qqy openssl
  script:
    - make check

stboot integration:
  stage: test
  image: debian:bookworm
  allow_failure: true
  before_script:
    - apt update
    - apt install -qqy qemu-system-x86 wget parted mtools cpio dosfstools git golang-1.19 golang-go unzip
  script:
    - git clone https://git.glasklar.is/system-transparency/core/stboot.git
    - cd stboot/integration && go work init && go work use . ../.. && ./qemu-boot-from-disk.sh
  artifacts:
    when: always
    paths:
      - stboot/integration/out/qemu.log
